'use client'

import { useState } from 'react'
import { X, Copy, CheckCheck, Sparkles, FileText, Wand2 } from 'lucide-react'

interface AIModalProps {
  isOpen: boolean
  onClose: () => void
  title: string
  content: string
  type: 'cover-letter' | 'parsed-jd'
}

export default function AIModal({ isOpen, onClose, title, content, type }: AIModalProps) {
  const [copied, setCopied] = useState(false)

  if (!isOpen) return null

  const handleCopy = async () => {
    await navigator.clipboard.writeText(content)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  return (
    <div className="modal-backdrop" onClick={e => e.target === e.currentTarget && onClose()}>
      <div className="modal-content" style={{ maxWidth: '700px' }}>
        {/* Header */}
        <div className="flex items-center justify-between mb-5">
          <div className="flex items-center gap-3">
            <div
              className="w-9 h-9 rounded-xl flex items-center justify-center"
              style={{ background: 'rgba(124,58,237,0.2)', border: '1px solid rgba(124,58,237,0.3)' }}
            >
              {type === 'cover-letter' ? (
                <Wand2 className="w-4 h-4" style={{ color: '#a855f7' }} />
              ) : (
                <FileText className="w-4 h-4" style={{ color: '#a855f7' }} />
              )}
            </div>
            <div>
              <h2 className="font-semibold text-white">{title}</h2>
              <div className="flex items-center gap-1 mt-0.5">
                <Sparkles className="w-3 h-3" style={{ color: '#a855f7' }} />
                <span className="text-xs" style={{ color: 'var(--text-muted)' }}>Generated by Claude AI</span>
              </div>
            </div>
          </div>
          <button
            onClick={onClose}
            id="ai-modal-close"
            className="btn-ghost p-2"
            style={{ padding: '6px' }}
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Content */}
        <div
          className="rounded-xl p-4 mb-5 overflow-y-auto"
          style={{
            background: 'var(--bg-secondary)',
            border: '1px solid var(--border)',
            maxHeight: '400px',
            whiteSpace: 'pre-wrap',
            fontSize: '0.875rem',
            lineHeight: '1.75',
            color: 'var(--text-primary)',
            fontFamily: type === 'cover-letter' ? 'inherit' : 'monospace',
          }}
        >
          {content}
        </div>

        {/* Actions */}
        <div className="flex justify-end gap-3">
          <button onClick={onClose} className="btn-secondary">
            Close
          </button>
          <button
            onClick={handleCopy}
            id="ai-modal-copy"
            className="btn-primary"
          >
            {copied ? (
              <><CheckCheck className="w-4 h-4" /> Copied!</>
            ) : (
              <><Copy className="w-4 h-4" /> Copy to Clipboard</>
            )}
          </button>
        </div>
      </div>
    </div>
  )
}
